Added russian translations
furcan/KioskBoard pull request #20
Opened 2021-04-08 10:47 UTC by vladislav-puzyrev

2021-04-08 16:14 UTC, furcan requested changes
Thank you.

2021-04-08 16:14 UTC, furcan commented on README.md
> +Additionally, KioskBoard includes 6 different language packages: `English` `Turkish` `Spanish` `German` `French` `Hungarian` `Russian`
...7 different...

2021-04-08 16:14 UTC, furcan commented on docs/index.html
> +        <p class="sec-desc">Additionally, KioskBoard includes 6 different language packages: <a target="_blank" rel="noopener noreferrer" href="https://github.com/furcan/KioskBoard/blob/master/dist/k
...7 different...

2021-04-09 06:29 UTC, vladislav-puzyrev commented
I suggest moving the letter `Ё` to the lower right corner because there is not enough space for it in the top row at the popular resolution of 1080px in width. I think this is not a big problem for the Russian language because on real keyboards the letter `Ё` is sometimes placed differently on the character ~ or / especially since many use the letter `Е` instead of `Ё`.

![image](https://user-images.githubusercontent.com/52296792/114137527-c271a700-9925-11eb-853c-3069731e0d01.png)

2021-04-09 07:43 UTC, furcan approved these changes

2021-04-09 07:43 UTC, merged